baseURL: http://tengweisong.com/
languageCode: en-sg
title: Teng Wei Song
publishDir: docs
theme: PaperMod

menu:
  main:
    - identifier: about
      name: About
      url: /about
      weight: 10
    - identifier: works
      name: Works
      url: /works
      weight: 20
    - identifier: posts
      name: Posts
      url: /posts
      weight: 30
    - identifier: tags
      name: Tags
      url: /tags
      weight: 40

params:
  homeInfoParams:
    title: Hi, I am Wei Song
    Content: --- A .NET developer based in Singapore.
  socialIcons:
    - name: github
      url: https://github.com/weisong0908/
    - name: linkedin
      url: https://github.com/weisong0908/
