baseURL: http://tengweisong.com/
languageCode: en-sg
title: Teng Wei Song
publishDir: docs
theme: PaperMod

menu:
  main:
    - identifier: about
      name: About
      url: /about
      weight: 1
    - identifier: posts
      name: Posts
      url: /posts
      weight: 2
    - identifier: tags
      name: Tags
      url: /tags
      weight: 2
